DROP TABLE IF EXISTS Sales;
CREATE TEMP TABLE Sales
(
"Year"  INTEGER NOT NULL,
Amount  INTEGER NOT NULL
);


INSERT INTO Sales ("Year", Amount) VALUES
(EXTRACT(YEAR FROM CURRENT_DATE), 352645),
(EXTRACT(YEAR FROM (CURRENT_DATE - INTERVAL '1 year')), 165565),
(EXTRACT(YEAR FROM (CURRENT_DATE - INTERVAL '1 year')), 254654),
(EXTRACT(YEAR FROM (CURRENT_DATE - INTERVAL '2 years')), 159521),
(EXTRACT(YEAR FROM (CURRENT_DATE - INTERVAL '2 years')), 251696),
(EXTRACT(YEAR FROM (CURRENT_DATE - INTERVAL '3 years')), 111894);

--SOLUTION
SELECT 
    MAX(CASE WHEN "Year" = 2025 THEN Amount END) AS "2025",
    MAX(CASE WHEN "Year" = 2024 THEN Amount END) AS "2024",
    MAX(CASE WHEN "Year" = 2023 THEN Amount END) AS "2023"
FROM Sales



